First attempt to upload packages

diff --git a/.github/workflows/publish-npm-version.yml b/.github/workflows/publish-npm-version.yml
--- a/.github/workflows/publish-npm-version.yml
+++ b/.github/workflows/publish-npm-version.yml
@@ -36,6 +36,7 @@ jobs:
           echo "Package $package_name@$package_version does not exist on the remote registry."
         fi
     - name: Print Package that would publish
+      if: 'false'
       run: |
         echo "Checking each package"
         for folder in "Packages"/*; do
@@ -45,9 +46,11 @@ jobs:
                 package_name=$(grep -oPm 1 '"name": "\K[^"]+' $file_to_print)
                 package_version=$(grep -oPm 1 '"version": "\K[^"]+' $file_to_print)
                 echo " - Checking if $package_name@$package_version exists"
+                # Deactivate exit on error
                 set +e
-                npm show "$package_name@$package_version" version
+                npm show "$package_name@$package_version" version &> /dev/null
                 exit_code=$?
+                # Reactivate exit on error
                 set -e
                 if [ $exit_code -eq 0 ]; then
                   echo "Package $package_name@$package_version exists on the remote registry."
@@ -60,19 +63,33 @@ jobs:
           fi
         done
     - name: Publish packages to NPM
-      if: 'false'
       run: |
         for folder in "Packages"/*; do
           if [ -d "$folder" ]; then
             file_to_publish="$folder/package.json"
         
             if [ -e "$file_to_publish" ]; then
-                echo "Publishing $file_to_publish"
-                cd "$folder" || exit 1
-
-                # npm publish
-
-                cd - || exit 2
+                package_name=$(grep -oPm 1 '"name": "\K[^"]+' $file_to_publish)
+                package_version=$(grep -oPm 1 '"version": "\K[^"]+' $file_to_publish)
+        
+                # Deactivate exit on error
+                set +e
+                npm show "$package_name@$package_version" version &> /dev/null
+                exit_code=$?
+                # Reactivate exit on error
+                set -e
+        
+                if [ $exit_code -eq 0 ]; then
+                  echo "Package $package_name@$package_version already exists."
+                else
+                  cd "$folder" || exit 1
+                  # Deactivate exit on error
+                  set +e
+                  npm publish
+                  # Reactivate exit on error
+                  set -e
+                  cd - || exit 2
+                fi
             else
                 echo "File package.json not found in $folder"
             fi
